name: Deploy Documentation

on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest

    container:
      image: python:3.12

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r sphinx sphinx-rtd-theme
      - name: Build Sphinx Documentation
        run: |
          mkdir -p build/docs/sphinx
          sphinx-build -b html docs/source build/docs/sphinx/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/sphinx/html
